[package]
edition = "2021"
name = "backend"
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
chacha20poly1305 = { workspace = true }
chrono = { workspace = true }
csv = { workspace = true }
figment = { workspace = true }
flate2 = { workspace = true }
futures-util = { workspace = true }
hickory-resolver = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
typeshare = { workspace = true }
url = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }
zip = { workspace = true }

cache = { path = "../cache" }
common = { path = "../runners/common" }
shared = { path = "../shared" }
