[package]
edition = "2021"
name = "backend"
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
chrono = { workspace = true }
figment = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
typeshare = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }

cache = { path = "../cache" }
common = { path = "../runners/common" }
shared = { path = "../shared" }

chacha20poly1305 = "0.10.1"
csv = "1.3.0"
flate2 = "1.0.28"
hickory-resolver = { version = "0.24.0", features = ["serde-config"] }
once_cell = "1.19.0"
regex = "1.10.3"
tokio-stream = "0.1.14"
url = "2.5.0"
utoipa = { version = "4.2.0", features = ["axum_extras", "chrono", "preserve_order", "uuid"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["axum"] }
zip = "0.6.6"
