[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.3"

serde = { workspace = true }
tracing = { workspace = true }
figment = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
tonic-build = "0.11.0"
